//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace plattform
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Doc_tbl
    {
        [DisplayName("ID")]
        public int id { get; set; }
        [DisplayName("Titel")]
        public string titel { get; set; }
        [DisplayName("Author")]
        public string author { get; set; }
        [DisplayName("Be-zeichnung")]
        public string bezeichnung { get; set; }
        [DisplayName("SerienNr")]
        public string SerieNr { get; set; }
        [DisplayName("Filename")]
        public string FileName { get; set; }
        public byte[] FileContent { get; set; }
        [Required]
        [DataType(DataType.Upload)]
        [Display(Name = "Select File")]

        public HttpPostedFileBase files { get; set; }
    }
}
