//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace plattform
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dokuments_tbl
    {
        public int id { get; set; }
        public string title { get; set; }
        public string author { get; set; }
        public string FileLocation { get; set; }
        public byte[] Datei { get; set; }
    }
}
