//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace plattform
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Dokuments_tbl
    {
        public int id { get; set; }
        [Required(ErrorMessage = "This Field is Required please")]
        public string title { get; set; }
        [Required(ErrorMessage = "This Field is Required please")]
        public string author { get; set; }
        
        [DisplayName(" Bezei chnung")]
        public string Bezeichnung { get; set; }
        [Required(ErrorMessage = "This Field is Required please")]
        public string SerieNr { get; set; }
        [Required(ErrorMessage = "This Field is Required please")]
        public byte[] FileContent { get; set; }
       
        public HttpPostedFileBase Datei { get; set; }
    }
}
