//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace plattform
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class user_tbl
    {
        public int id { get; set; }
        public string vorname { get; set; }
        public string nachname { get; set; }
        public string adresse { get; set; }
        public string email { get; set; }
        public string mobile { get; set; }
        [Required]
        [MinLength(6,ErrorMessage="Mindesten 6 Zeichen Bitte ")]
        [DataType(DataType.Password)]
        public string password { get; set; }
        public string title { get; set; }
        public Nullable<bool> IsEmailverified { get; set; }
        public Nullable<System.Guid> ActivationCode { get; set; }
    }
}
